### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by JavaLuigi** [OnyxfireInc/vss-backup#1]
Do you have any intention to implement a restore feature?
Regards
Ludger

**Comment by lancefogle** [comment]
@JavaLuigi 

Sorry for the delay. I only just saw your submitted issue.

At this point, no, as this was meant really as a simple file-level backup that works even while a filesystem is in use. That being said, **restoring** to a filesystem that is in use on Windows is a bit more complex (file locking, etc).

It wouldn't take much to write a simple restore function given the passed path to restore from and what drive to restore to; you just can't guarantee results unless it is a data drive that has nothing holding any file locks (applications, etc.)

If you would like to contribute some code to implement it in the form of a pull request that would be ok but I don't think we will be spending time on it at least in the near future.
